from django import forms
from .models import Order

COUNTRY_CHOICES = {
    'Afghanistan': 'Afghanistan',
    'Albania': 'Albania',
    'Algeria': 'Algeria',
    'Andorra': 'Andorra',
    'Angola': 'Angola',
    'Antigua and Barbuda': 'Antigua and Barbuda',
    'Argentina': 'Argentina',
    'Armenia': 'Armenia',
    'Australia': 'Australia',
    'Austria': 'Austria',
    'Azerbaijan': 'Azerbaijan',
    'Bahamas': 'Bahamas',
    'Bahrain': 'Bahrain',
    'Bangladesh': 'Bangladesh',
    'Barbados': 'Barbados',
    'Belarus': 'Belarus',
    'Belgium': 'Belgium',
    'Belize': 'Belize',
    'Benin': 'Benin',
    'Bhutan': 'Bhutan',
    'Bolivia': 'Bolivia',
    'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
    'Botswana': 'Botswana',
    'Brazil': 'Brazil',
    'Brunei': 'Brunei',
    'Bulgaria': 'Bulgaria',
    'Burkina Faso': 'Burkina Faso',
    'Burundi': 'Burundi',
    'Cambodia': 'Cambodia',
    'Cameroon': 'Cameroon',
    'Canada': 'Canada',
    'Cape Verde': 'Cape Verde',
    'Central African Republic': 'Central African Republic',
    'Chad': 'Chad',
    'Chile': 'Chile',
    'China': 'China',
    'Colombia': 'Colombia',
    'Comoros': 'Comoros',
    'Congo': 'Congo',
    'Costa Rica': 'Costa Rica',
    'Croatia': 'Croatia',
    'Cuba': 'Cuba',
    'Cyprus': 'Cyprus',
    'Czech Republic': 'Czech Republic',
    'Denmark': 'Denmark',
    'Djibouti': 'Djibouti',
    'Dominica': 'Dominica',
    'Dominican Republic': 'Dominican Republic',
    'East Timor': 'East Timor',
    'Ecuador': 'Ecuador',
    'Egypt': 'Egypt',
    'El Salvador': 'El Salvador',
    'Equatorial Guinea': 'Equatorial Guinea',
    'Eritrea': 'Eritrea',
    'Estonia': 'Estonia',
    'Ethiopia': 'Ethiopia',
    'Fiji': 'Fiji',
    'Finland': 'Finland',
    'France': 'France',
    'Gabon': 'Gabon',
    'Gambia': 'Gambia',
    'Georgia': 'Georgia',
    'Germany': 'Germany',
    'Ghana': 'Ghana',
    'Greece': 'Greece',
    'Grenada': 'Grenada',
    'Guatemala': 'Guatemala',
    'Guinea': 'Guinea',
    'Guinea-Bissau': 'Guinea-Bissau',
    'Guyana': 'Guyana',
    'Haiti': 'Haiti',
    'Honduras': 'Honduras',
    'Hungary': 'Hungary',
    'Iceland': 'Iceland',
    'India': 'India',
    'Indonesia': 'Indonesia',
    'Iran': 'Iran',
    'Iraq': 'Iraq',
    'Ireland': 'Ireland',
    'Israel': 'Israel',
    'Italy': 'Italy',
    'Jamaica': 'Jamaica',
    'Japan': 'Japan',
    'Jordan': 'Jordan',
    'Kazakhstan': 'Kazakhstan',
    'Kenya': 'Kenya',
    'Kiribati': 'Kiribati',
    'Kuwait': 'Kuwait',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Laos': 'Laos',
    'Latvia': 'Latvia',
    'Lebanon': 'Lebanon',
    'Lesotho': 'Lesotho',
    'Liberia': 'Liberia',
    'Libya': 'Libya',
    'Liechtenstein': 'Liechtenstein',
    'Lithuania': 'Lithuania',
    'Luxembourg': 'Luxembourg',
    'Madagascar': 'Madagascar',
    'Malawi': 'Malawi',
    'Malaysia': 'Malaysia',
    'Maldives': 'Maldives',
    'Mali': 'Mali',
    'Malta': 'Malta',
    'Marshall Islands': 'Marshall Islands',
    'Mauritania': 'Mauritania',
    'Mauritius': 'Mauritius',
    'Mexico': 'Mexico',
    'Micronesia': 'Micronesia',
    'Moldova': 'Moldova',
    'Monaco': 'Monaco',
    'Mongolia': 'Mongolia',
    'Montenegro': 'Montenegro',
    'Morocco': 'Morocco',
    'Mozambique': 'Mozambique',
    'Myanmar': 'Myanmar',
    'Namibia': 'Namibia',
    'Nauru': 'Nauru',
    'Nepal': 'Nepal',
    'Netherlands': 'Netherlands',
    'New Zealand': 'New Zealand',
    'Nicaragua': 'Nicaragua',
    'Niger': 'Niger',
    'Nigeria': 'Nigeria',
    'Norway': 'Norway',
    'Oman': 'Oman',
    'Pakistan': 'Pakistan',
    'Palau': 'Palau',
    'Panama': 'Panama',
    'Papua New Guinea': 'Papua New Guinea',
    'Paraguay': 'Paraguay',
    'Peru': 'Peru',
    'Philippines': 'Philippines',
    'Poland': 'Poland',
    'Portugal': 'Portugal',
    'Qatar': 'Qatar',
    'Romania': 'Romania',
    'Russia': 'Russia',
    'Rwanda': 'Rwanda',
    'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
    'Saint Lucia': 'Saint Lucia',
    'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
    'Samoa': 'Samoa',
    'San Marino': 'San Marino',
    'Sao Tome and Principe': 'Sao Tome and Principe',
    'Saudi Arabia': 'Saudi Arabia',
    'Senegal': 'Senegal',
    'Serbia': 'Serbia',
    'Seychelles': 'Seychelles',
    'Sierra Leone': 'Sierra Leone',
    'Singapore': 'Singapore',
    'Slovakia': 'Slovakia',
    'Slovenia': 'Slovenia',
    'Solomon Islands': 'Solomon Islands',
    'Somalia': 'Somalia',
    'South Africa': 'South Africa',
    'South Sudan': 'South Sudan',
    'Spain': 'Spain',
    'Sri Lanka': 'Sri Lanka',
    'Sudan': 'Sudan',
    'Suriname': 'Suriname',
    'Swaziland': 'Swaziland',
    'Sweden': 'Sweden',
    'Switzerland': 'Switzerland',
    'Syria': 'Syria',
    'Taiwan': 'Taiwan',
    'Tajikistan': 'Tajikistan',
    'Tanzania': 'Tanzania',
    'Thailand': 'Thailand',
    'Togo': 'Togo',
    'Tonga': 'Tonga',
    'Trinidad and Tobago': 'Trinidad and Tobago',
    'Tunisia': 'Tunisia',
    'Turkey': 'Turkey',
    'Turkmenistan': 'Turkmenistan',
    'Tuvalu': 'Tuvalu',
    'Uganda': 'Uganda',
    'Ukraine': 'Ukraine',
    'United Arab Emirates': 'United Arab Emirates',
    'United Kingdom': 'United Kingdom',
    'United States': 'United States',
    'Uruguay': 'Uruguay',
    'Uzbekistan': 'Uzbekistan',
    'Vanuatu': 'Vanuatu',
    'Vatican City': 'Vatican City',
    'Venezuela': 'Venezuela',
    'Vietnam': 'Vietnam',
    'Yemen': 'Yemen',
    'Zambia': 'Zambia',
    'Zimbabwe': 'Zimbabwe'
}

ZIP_CHOICES = [
    ('+93', 'Afghanistan +93'),
    ('+355', 'Albania +355'),
    ('+213', 'Algeria +213'),
    ('+1-684', 'American Samoa +1-684'),
    ('+376', 'Andorra +376'),
    ('+244', 'Angola +244'),
    ('+1-264', 'Anguilla +1-264'),
    ('+672', 'Antarctica'),
    ('+1-268', 'Antigua and Barbuda +1-268'),
    ('+54', 'Argentina +54'),
    ('+374', 'Armenia +374'),
    ('+297', 'Aruba +297'),
    ('+61', 'Australia +61'),
    ('+43', 'Austria +43'),
    ('+994', 'Azerbaijan'),
    ('+1-242', 'Bahamas'),
    ('+973', 'Bahrain'),
    ('+880', 'Bangladesh'),
    ('+1-246', 'Barbados'),
    ('+375', 'Belarus'),
    ('+32', 'Belgium'),
    ('+501', 'Belize'),
    ('+229', 'Benin'),
    ('+1-441', 'Bermuda'),
    ('+975', 'Bhutan'),
    ('+591', 'Bolivia'),
    ('+387', 'Bosnia and Herzegovina'),
    ('+267', 'Botswana'),
    ('+55', 'Brazil'),
    ('+246', 'British Indian Ocean Territory'),
    ('+1-284', 'British Virgin Islands'),
    ('+673', 'Brunei'),
    ('+359', 'Bulgaria'),
    ('+226', 'Burkina Faso'),
    ('+257', 'Burundi'),
    ('+855', 'Cambodia'),
    ('+237', 'Cameroon'),
    ('+1', 'Canada'),
    ('+238', 'Cape Verde'),
    ('+1-345', 'Cayman Islands'),
    ('+236', 'Central African Republic'),
    ('+235', 'Chad'),
    ('+56', 'Chile'),
    ('+86', 'China'),
    ('+61', 'Christmas Island'),
    ('+61', 'Cocos Islands'),
    ('+57', 'Colombia'),
    ('+269', 'Comoros'),
    ('+682', 'Cook Islands'),
    ('+506', 'Costa Rica'),
    ('+385', 'Croatia'),
    ('+53', 'Cuba'),
    ('+599', 'Curacao'),
    ('+357', 'Cyprus'),
    ('+420', 'Czech Republic'),
    ('+243', 'Democratic Republic of the Congo'),
    ('+45', 'Denmark'),
    ('+253', 'Djibouti'),
    ('+1-767', 'Dominica'),
    ('+1-809', 'Dominican Republic'),
    ('+1-829', 'Dominican Republic'),
    ('+1-849', 'Dominican Republic'),
    ('+670', 'East Timor'),
    ('+593', 'Ecuador'),
    ('+20', 'Egypt'),
    ('+503', 'El Salvador'),
    ('+240', 'Equatorial Guinea'),
    ('+291', 'Eritrea'),
    ('+372', 'Estonia'),
    ('+251', 'Ethiopia'),
    ('+500', 'Falkland Islands'),
    ('+298', 'Faroe Islands'),
    ('+679', 'Fiji'),
    ('+358', 'Finland'),
    ('+33', 'France'),
    ('+689', 'French Polynesia'),
    ('+241', 'Gabon'),
    ('+220', 'Gambia'),
    ('+995', 'Georgia'),
    ('+49', 'Germany'),
    ('+233', 'Ghana'),
    ('+350', 'Gibraltar'),
    ('+30', 'Greece'),
    ('+299', 'Greenland'),
    ('+1-473', 'Grenada'),
    ('+1-671', 'Guam'),
    ('+502', 'Guatemala'),
    ('+44', 'Guernsey'),
    ('+224', 'Guinea'),
    ('+245', 'Guinea-Bissau'),
    ('+592', 'Guyana'),
    ('+509', 'Haiti'),
    ('+504', 'Honduras'),
    ('+852', 'Hong Kong'),
    ('+36', 'Hungary'),
    ('+354', 'Iceland'),
    ('+91', 'India'),
    ('+62', 'Indonesia'),
    ('+98', 'Iran'),
    ('+964', 'Iraq'),
    ('+353', 'Ireland'),
    ('+44', 'Isle of Man'),
    ('+972', 'Israel'),
    ('+39', 'Italy'),
    ('+225', "Côte d'Ivoire"),
    ('+1-876', 'Jamaica'),
    ('+81', 'Japan'),
    ('+44', 'Jersey'),
    ('+962', 'Jordan'),
    ('+7', 'Kazakhstan'),
    ('+254', 'Kenya'),
    ('+686', 'Kiribati'),
    ('+383', 'Kosovo'),
    ('+965', 'Kuwait'),
    ('+996', 'Kyrgyzstan'),
    ('+856', 'Laos'),
    ('+371', 'Latvia'),
    ('+961', 'Lebanon'),
    ('+266', 'Lesotho'),
    ('+231', 'Liberia'),
    ('+218', 'Libya'),
    ('+423', 'Liechtenstein'),
    ('+370', 'Lithuania'),
    ('+352', 'Luxembourg'),
    ('+853', 'Macau'),
    ('+389', 'Macedonia'),
    ('+261', 'Madagascar'),
    ('+265', 'Malawi'),
    ('+60', 'Malaysia'),
    ('+960', 'Maldives'),
    ('+223', 'Mali'),
    ('+356', 'Malta'),
    ('+692', 'Marshall Islands'),
    ('+222', 'Mauritania'),
    ('+230', 'Mauritius'),
    ('+262', 'Mayotte'),
    ('+52', 'Mexico'),
    ('+691', 'Micronesia'),
    ('+373', 'Moldova'),
    ('+377', 'Monaco'),
    ('+976', 'Mongolia'),
    ('+382', 'Montenegro'),
    ('+1-664', 'Montserrat'),
    ('+212', 'Morocco'),
    ('+258', 'Mozambique'),
    ('+95', 'Myanmar'),
    ('+264', 'Namibia'),
    ('+674', 'Nauru'),
    ('+977', 'Nepal'),
    ('+31', 'Netherlands'),
    ('+599', 'Netherlands Antilles'),
    ('+687', 'New Caledonia'),
    ('+64', 'New Zealand'),
    ('+505', 'Nicaragua'),
    ('+227', 'Niger'),
    ('+234', 'Nigeria'),
    ('+683', 'Niue'),
    ('+850', 'North Korea'),
    ('+1-670', 'Northern Mariana Islands'),
    ('+47', 'Norway'),
    ('+968', 'Oman'),
    ('+92', 'Pakistan'),
    ('+680', 'Palau'),
    ('+970', 'Palestine'),
    ('+507', 'Panama'),
    ('+675', 'Papua New Guinea'),
    ('+595', 'Paraguay'),
    ('+51', 'Peru'),
    ('+63', 'Philippines'),
    ('+64', 'Pitcairn'),
    ('+48', 'Poland'),
    ('+351', 'Portugal'),
    ('+1-787', 'Puerto Rico'),
    ('+1-939', 'Puerto Rico'),
    ('+974', 'Qatar'),
    ('+242', 'Republic of the Congo'),
    ('+262', 'Reunion'),
    ('+40', 'Romania'),
    ('+7', 'Russia'),
    ('+250', 'Rwanda'),
    ('+590', 'Saint Barthelemy'),
    ('+290', 'Saint Helena'),
    ('+1-869', 'Saint Kitts and Nevis'),
    ('+1-758', 'Saint Lucia'),
    ('+590', 'Saint Martin'),
    ('+508', 'Saint Pierre and Miquelon'),
    ('+1-784', 'Saint Vincent and the Grenadines'),
    ('+685', 'Samoa'),
    ('+378', 'San Marino'),
    ('+239', 'Sao Tome and Principe'),
    ('+966', 'Saudi Arabia'),
    ('+221', 'Senegal'),
    ('+381', 'Serbia'),
    ('+248', 'Seychelles'),
    ('+232', 'Sierra Leone'),
    ('+65', 'Singapore'),
    ('+1-721', 'Sint Maarten'),
    ('+421', 'Slovakia'),
    ('+386', 'Slovenia'),
    ('+677', 'Solomon Islands'),
    ('+252', 'Somalia'),
    ('+27', 'South Africa'),
    ('+82', 'South Korea'),
    ('+211', 'South Sudan'),
    ('+34', 'Spain'),
    ('+94', 'Sri Lanka'),
    ('+249', 'Sudan'),
    ('+597', 'Suriname'),
    ('+47', 'Svalbard and Jan Mayen'),
    ('+268', 'Swaziland'),
    ('+46', 'Sweden'),
    ('+41', 'Switzerland'),
    ('+963', 'Syria'),
    ('+886', 'Taiwan'),
    ('+992', 'Tajikistan'),
    ('+255', 'Tanzania'),
    ('+66', 'Thailand'),
    ('+228', 'Togo'),
    ('+690', 'Tokelau'),
    ('+676', 'Tonga'),
    ('+1-868', 'Trinidad and Tobago'),
    ('+216', 'Tunisia'),
    ('+90', 'Turkey'),
    ('+993', 'Turkmenistan'),
    ('+1-649', 'Turks and Caicos Islands'),
    ('+688', 'Tuvalu'),
    ('+1-340', 'U.S. Virgin Islands'),
    ('+256', 'Uganda'),
    ('+380', 'Ukraine'),
    ('+971', 'United Arab Emirates'),
    ('+44', 'United Kingdom'),
    ('+1', 'United States'),
    ('+598', 'Uruguay'),
    ('+998', 'Uzbekistan'),
    ('+678', 'Vanuatu'),
    ('+379', 'Vatican'),
    ('+58', 'Venezuela'),
    ('+84', 'Vietnam'),
    ('+681', 'Wallis and Futuna'),
    ('+212', 'Western Sahara'),
    ('+967', 'Yemen'),
    ('+260', 'Zambia'),
    ('+263', 'Zimbabwe'),
]
 
DELIVERY_METHOD = (
        ("DHL", "DHL"),
        ("Colissimo", "Colissimo"),
    )

PAYMENT_METHOD = (
        ("Card", "Card"),
        ("Paypal", "Paypal"),
    )
class OrderForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "inputText", "name": "first_name", "placeholder":""}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "inputText", "name": "last_name", "placeholder":""}))
    phone = forms.CharField(required=True, widget=forms.TextInput(attrs={"class": "number", "name": "phone"}))
    email = forms.CharField(required=True, widget=forms.EmailInput(attrs={"class": "inputText", "name": "email", "placeholder":""}))
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, widget=forms.Select(attrs={"class": "country-select", "name": "country", "id":"country"}))    
    address_line_1 = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"", "name":"address_line_1"}))
    address_line_1 = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"cmyPass", "name":"address_line_2"}))
    postcode = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"postcode", "name":"postcode"}))
    city = forms.CharField(widget=forms.TextInput(attrs={"class": "", "id":"city", "name":"city"}))
    zip_code = forms.ChoiceField(choices=ZIP_CHOICES, widget=forms.Select(attrs={"class": "code-phone", "id":"zip_code", "name":"zip_code"}))
    delivery_method = forms.ChoiceField(choices=DELIVERY_METHOD, widget=forms.RadioSelect(attrs={"name": "delivery_method", "class": "delivery_method_inputs"}))
    payment_method = forms.ChoiceField(choices=PAYMENT_METHOD, widget=forms.RadioSelect(attrs={"name": "payment_method", "class": "payment_method_inputs"}))

    class Meta:
        model = Order
        fields = ['first_name', 'zip_code', 'last_name', 'phone', 'email', 'address_line_1', 'address_line_2',
                  'country', 'city', 'postcode', 'payment_method', 'delivery_method', 'postcode']
        widgets = {
            'delivery_method': forms.RadioSelect(),
            'payment_method': forms.RadioSelect(),
        }
    def __init__(self, *args, **kwargs):
        user_country = kwargs.pop('user_country', None)
        super(OrderForm, self).__init__(*args, **kwargs)
        
        # Modifier les choix disponibles pour delivery_method en fonction du pays de l'utilisateur
        if user_country == 'FR':
            self.fields['delivery_method'].choices = [('Colissimo', 'Colissimo')]
            self.fields['delivery_method'].initial = 'Colissimo'
            self.fields['payment_method'].initial = 'Card'

        else:
            # Assumez ici vos autres options de livraison par défaut
            self.fields['delivery_method'].choices = [('DHL', 'DHL')]
            self.fields['delivery_method'].initial = 'DHL'
            self.fields['payment_method'].initial = 'Card'

        